### ISSUE TITLE
Support other paths for .env

### ISSUE THREAD

**Issue by klarkc** [nsaunders/purescript-dotenv#42]
Do you plan to support alternative paths for the `.env` files? I was trying to have a default `.env` and a local `.env.local` but I believe it's not supported right now, that' correct?

**Comment by nsaunders** [comment]
Hi @klarkc! I wonder if the [`loadContents`](https://github.com/nsaunders/purescript-dotenv/blob/master/src/Dotenv.purs#L41-L44) function might work for you in this case? You would just need to read the file contents using e.g. [`readTextFile`](https://pursuit.purescript.org/packages/purescript-node-fs/9.1.0/docs/Node.FS.Aff#v:readTextFile) and then apply the `loadContents` function to that string. Please let me know what you think!

**Comment by klarkc** [comment]
@nsaunders yes that should work, thanks.
